version: "3.8"

services:
  mysql:
    image: mysql:latest
    # container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: car_game_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: ["sh", "-c", "./wait-for-it.sh mysql:3306 -- npm run dev"]
    restart: unless-stopped

  client:
    build:
      context: ./client/dashboard
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mysql_data:
